name: Docker Build & Publish

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/docker.yml"
      - ".vscode/**"
      - "doc/**"
      - "lifecycle/**"
      - ".gitignore"
      - "README.md"
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/docker.yml"
      - ".vscode/**"
      - "doc/**"
      - "lifecycle/**"
      - ".gitignore"
      - "README.md"
  workflow_dispatch:


jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo + submodules
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Build and push the image
        run: |
          docker login --username akurosia --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/akurosia/for-web:latest
          docker push ghcr.io/akurosia/for-web:latest
